version: '3.7'

services:
  localstack:
    image: localstack/localstack:3
    ports:
      - 4566:4566
    environment:
      - SERVICES=kms,dynamodb
      - AWS_DEFAULT_REGION=ap-south-1
      - DYNAMODB_IN_MEMORY=1
    volumes:
      - ./localstack/init-dynamodb.sh:/etc/localstack/init/ready.d/init-dynamodb.sh
      - ./localstack/init-kms.sh:/etc/localstack/init/ready.d/init-kms.sh
    networks:
      - cipherinator
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
      - localstack
    environment:
      ACTIVE_PROFILE: local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: 'ap-south-1'
      AWS_ENDPOINT_URL: 'http://localstack:4566'
      AWS_KMS_KEY_ID: '00000000-1111-2222-3333-000000000000'
    networks:
      - cipherinator

networks:
  cipherinator:
