spring:
  profiles:
    active: ${ACTIVE_PROFILE}

com:
  behl:
    aws:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-access-key: ${AWS_SECRET_ACCESS_KEY}
      region: ${AWS_REGION}
      endpoint: ${AWS_ENDPOINT_URL}