name: Database field encryptor in JPA using KMS build

on:
  push:
    branches: 
      - "*"
    paths: 
      - article-samples/pii-encryptor-jpa/**
      - .github/workflows/pii-encryptor-jpa.yml
  pull_request:
    branches: 
      - main
    paths: 
      - article-samples/pii-encryptor-jpa/**
      - .github/workflows/pii-encryptor-jpa.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./article-samples/pii-encryptor-jpa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: maven

      - name: Compile project
        run: mvn compile

      - name: Run Integration Tests
        run: mvn integration-test verify
